services:
  mysql:
    image: mysql:latest
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=root
    volumes:
      - minilibsecure-data:/var/lib/mysql

volumes:
  minilibsecure-data:
