services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile.backend
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    depends_on:
      - mysql
    networks:
      - minilibsecure-network
    entrypoint: >
      sh -c "
        npx prisma generate &&        
        npx prisma db push         
      "

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    env_file:
      - ./frontend/.env
    networks:
      - minilibsecure-network
    command: npm run dev

  mysql:
    container_name: db
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: minilibsecure
    volumes:
      - minilibsecure-data:/var/lib/mysql
    networks:
      - minilibsecure-network

volumes:
  minilibsecure-data:

networks:
  minilibsecure-network:
    driver: bridge
